### ISSUE TITLE
20150819朝会

### ISSUE THREAD

**Issue by tyouhou** [enpitut/CAST#2]

**Comment by your3i** [comment]
![img_0530](https://cloud.githubusercontent.com/assets/12044194/9348958/bff9958c-4679-11e5-8340-a4e93c20e2f5.JPG)

**Comment by your3i** [comment]
![img_0496](https://cloud.githubusercontent.com/assets/12044194/9348960/cb64b92e-4679-11e5-9a64-450f478f1f1d.JPG)

**Comment by your3i** [comment]
![img_0494](https://cloud.githubusercontent.com/assets/12044194/9348963/dca1003a-4679-11e5-8895-6568aa5f4b89.JPG)
